// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WAD.CW1._00013292.Data;

#nullable disable

namespace WAD.CW1._00013292.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240320084653_InitialCommit")]
    partial class InitialCommit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WAD.CW1._00013292.Models.KeyItem", b =>
                {
                    b.Property<int>("KeyItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KeyItemId"));

                    b.Property<int>("KeyTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KeyItemId");

                    b.HasIndex("KeyTypeId");

                    b.ToTable("KeyItems");
                });

            modelBuilder.Entity("WAD.CW1._00013292.Models.KeyType", b =>
                {
                    b.Property<int>("KeyTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KeyTypeId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KeyTypeId");

                    b.ToTable("KeyTypes");

                    b.HasData(
                        new
                        {
                            KeyTypeId = 1,
                            Description = "Keys for API access",
                            Name = "API Key"
                        },
                        new
                        {
                            KeyTypeId = 2,
                            Description = "Keys for software licensing",
                            Name = "License Key"
                        });
                });

            modelBuilder.Entity("WAD.CW1._00013292.Models.KeyItem", b =>
                {
                    b.HasOne("WAD.CW1._00013292.Models.KeyType", "KeyType")
                        .WithMany("KeyItems")
                        .HasForeignKey("KeyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KeyType");
                });

            modelBuilder.Entity("WAD.CW1._00013292.Models.KeyType", b =>
                {
                    b.Navigation("KeyItems");
                });
#pragma warning restore 612, 618
        }
    }
}
